Sprint 5
Sapr0nov/pegas-alias pull request #2
Opened 2022-09-27 17:06 UTC by Starushchenko

### Какую задачу решаем
Настройка проекта, вёрстка

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-10-12 13:39 UTC, shoom1337 requested changes
Хорошая работа. Комменты по большей части для расширения кругозора и обмена опытом.
Критичных замечаний нет.
Если есть какие-то вопросы, можно обсудить в чате.

2022-10-12 13:39 UTC, shoom1337 commented on packages/client/src/components/round-board/round-board.tsx
> +  }
❓ Специфичные функции лучше комментировать в формате: "Делает то-то". На эту пару минут посмотрел, прежде чем понял для чего она нужно. Если бы был коммент, то было бы проще.

2022-10-12 13:39 UTC, shoom1337 commented on packages/client/src/components/winner/winner.tsx
> +export const Winner: FC<IWinner> = ({ nameWinnerTeam, score }) => {
ℹ️ Бросилось в глаза: в каких-то компонентах React.FC, где-то заимпорчен FC. Нужно придерживаться одного стиля.

2022-10-12 13:39 UTC, shoom1337 commented on packages/client/src/pages/change-password.tsx
> +          <FormField
🚀 FormField выглядит по-взрослому!

2022-10-12 13:39 UTC, shoom1337 commented on packages/client/src/pages/change-password.tsx
> +              onClick: () => navigate('/profile')
❓ Функцию нужно вынести в хендлер и вспомнить про useCallback.

2022-10-12 13:39 UTC, shoom1337 commented on packages/client/src/pages/profile.tsx
> +            })}
ℹ️  Параметры валидации повторяются по всему файлу, можно подумать как их вынести и переиспользовать.

2022-10-12 13:57 UTC, Starushchenko commented on packages/client/src/components/avatar/avatar.scss
> +.avatar-edit {
Осознанно не использовали нестинг для простоты поиска класса по вхождению, это критично ?)

2022-10-17 14:32 UTC, Starushchenko commented on packages/client/src/components/modal/modal.scss
> +.mb-28{
Думаю, от такого чуть позже избавлюсь. Пока добавил в файл scaffolding, у нас там живут всякие .hidden, .visually-hidden

2022-10-18 07:23 UTC, merged